### ISSUE TITLE
FileUriExposedException exception on click of send button

### ISSUE THREAD

**Issue by kaustav07** [webianks/EasyFeedback#5]
FileUriExposedException thrown on click of send button as it is restricted on API24+

check out this [https://medium.com/@ali.muzaffar/what-is-android-os-fileuriexposedexception-and-what-you-can-do-about-it-70b9eb17c6d0](url)

**Comment by mustafa-demir** [comment]
Same problem here. 

For now, I called EasyFeedback without system info and log reports on API 24+. I will wait for the fix.

**Comment by ameerhamza6733** [comment]
same error

**Comment by JSBerrocoso** [comment]
Same problem @webianks 
Traces: 
`2018-11-06 11:40:57.356 27416-27416/com.jertelabs.trailrunreader.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jertelabs.trailrunreader.app, PID: 27416
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.jertelabs.miapp.app/cache/deviceInf.txt exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10486)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
        at android.app.Activity.startActivityForResult(Activity.java:4564)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4522)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4883)
        at android.app.Activity.startActivity(Activity.java:4851)
        at com.webianks.easy_feedback.FeedbackActivity.sendEmail(FeedbackActivity.java:304)
        at com.webianks.easy_feedback.FeedbackActivity.onClick(FeedbackActivity.java:338)
        at android.view.View.performClick(View.java:6891)
        at android.widget.TextView.performClick(TextView.java:12651)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by JSBerrocoso** [comment]
Same problem @webianks
Traces:

`2018-11-06 11:40:57.356 27416-27416/com.jertelabs.miapp.app E/AndroidRuntime: FATAL EXCEPTION: main Process: com.jertelabs.miapp.app, PID: 27416 android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.jertelabs.miapp.app/cache/deviceInf.txt exposed beyond app through ClipData.Item.getUri() at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958) at android.net.Uri.checkFileUriExposed(Uri.java:2356) at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944) at android.content.Intent.prepareToLeaveProcess(Intent.java:10480) at android.content.Intent.prepareToLeaveProcess(Intent.java:10486) at android.content.Intent.prepareToLeaveProcess(Intent.java:10465) at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616) at android.app.Activity.startActivityForResult(Activity.java:4564) at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767) at android.app.Activity.startActivityForResult(Activity.java:4522) at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754) at android.app.Activity.startActivity(Activity.java:4883) at android.app.Activity.startActivity(Activity.java:4851) at com.webianks.easy_feedback.FeedbackActivity.sendEmail(FeedbackActivity.java:304) at com.webianks.easy_feedback.FeedbackActivity.onClick(FeedbackActivity.java:338) at android.view.View.performClick(View.java:6891) at android.widget.TextView.performClick(TextView.java:12651) at android.view.View$PerformClick.run(View.java:26083) at android.os.Handler.handleCallback(Handler.java:789) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6938) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by webianks** [comment]
Have fixed this. Will push the changes and update the library soon.

**Comment by Gerrix90** [comment]
In order to avoid crash write this code snippet before calling EasyFeedback library:

`if(Build.VERSION.SDK_INT>=24){
   try{
      Method m = StrictMode.class.getMethod("disableDeathOnFileUriExposure");
      m.invoke(null);
   }catch(Exception e){
      e.printStackTrace();
   }
}`
