### ISSUE TITLE
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/my.package/cache/deviceInf.txt exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by Gerrix90** [webianks/EasyFeedback#9]
You should fix this:

Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/my.package/cache/deviceInf.txt exposed beyond app through ClipData.Item.getUri()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1975)
       at android.net.Uri.checkFileUriExposed(Uri.java:2363)
       at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9944)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9950)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:9929)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1622)
       at android.app.Activity.startActivityForResult(Activity.java:4751)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:4691)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
       at android.app.Activity.startActivity(Activity.java:5112)
       at android.app.Activity.startActivity(Activity.java:5080)
       at com.webianks.easy_feedback.FeedbackActivity.sendEmail(FeedbackActivity.java:304)
       at com.webianks.easy_feedback.FeedbackActivity.onClick(FeedbackActivity.java:338)
       at android.view.View.performClick(View.java:6291)
       at android.view.View$PerformClick.run(View.java:24931)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

-----------------------------------------------------

I fixed this issue by adding:

if(Build.VERSION.SDK_INT>=24){
   try{
      Method m = StrictMode.class.getMethod("disableDeathOnFileUriExposure");
      m.invoke(null);
   }catch(Exception e){
      e.printStackTrace();
   }
}

**Comment by webianks** [comment]
Use `implementation 'com.webianks.library:easy-feedback:1.0.5'`

**Comment by Gerrix90** [comment]
> Which library version you are using?

I am using `implementation 'com.webianks.library:easy-feedback:1.0.2'`

I will update library. 

Thank you for the librirary!
